[build]
builder = "NIXPACKS"
buildCommand = "npm install && npm install --prefix ../frontend && npm run build --prefix ../frontend"

[deploy]
startCommand = "node src/index.js"
healthcheckPath = "/api/health"
healthcheckTimeout = 30
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 3
